### ISSUE TITLE
您好，请问代码统计的部分

### ISSUE THREAD

**Issue by GoodManWEN** [zhengfan2014/zhengfan2014#1]
从V2EX访问到你的连接，很喜欢您主页里的`Recently I'm coding in...`的部分，可以很清楚地显示代码成分，但是我试着调用了一下发现并不支持我的gh账号，请问是需要做什么特殊接入吗，谢谢

**Comment by zhengfan2014** [comment]
首先，需要在codestats.net注册一个账号
然后，用注册的账号在codestats.net上弄到一个apikey，并确保`https://codestats.net/users/你的用户名`这个链接可以访问
最后，vscode安装codestats.net提供的插件，绑定上一步的apikey，把readme.md指向的链接里的`zhengfan2014`换成你自己的用户名。

关于图表的更多用法，可以参考这里：https://github.com/WEGFan/codestats-profile-readme ~~（我也是从这里白嫖的😂）~~

正在准备4月的考试，没法写一篇详细的保姆级教程，希望可以帮到您😂

**Comment by GoodManWEN** [comment]
感谢回复，我以为这个是github的commit统计，如果需要插件的反倒作用不大了，因为我基本只用vscode写前端语言。anyway thanks
